# vim: ft=dockerfile
FROM python:3.10-alpine AS builder
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade poetry
COPY  ./backupr /backupr/backupr
COPY  ./poetry.lock /backupr/poetry.lock
COPY  ./pyproject.toml /backupr/pyproject.toml
RUN cd /backupr && poetry build --format=wheel

FROM python:3.10-alpine AS backupr
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
COPY --from=builder /backupr/dist /tmp/backupr
RUN pip install /tmp/backupr/*.whl && rm -rf /tmp/swifty
COPY docker/entrypoint.sh /usr/bin
ENTRYPOINT /usr/bin/entrypoint.sh
