name: Lint and Test
on: [push]
jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10","3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry env info
          poetry install
      - name: Lint
        run: |
          poetry run scripts/lint.sh
      - name: Run all tests (unit|integration)
        env:
          B2_KEY_NAME: ${{ secrets.B2_KEY_NAME}}
          B2_BUCKET_NAME: ${{ secrets.B2_BUCKET_NAME }}
          B2_APPLICATION_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
        run: |
          poetry run scripts/all-tests.sh
